### ISSUE TITLE
Customize port to replace the default 80

### ISSUE THREAD

**Issue by schklom** [rotki/rotki#5055]
## Abstract

It would be great if we could choose the port that Rotki uses, instead of the default 80.

## Motivation

Using Docker, I pass Rotki behind a vpn container.
I want to expose Rotki's port 80, but another container behind the vpn also needs port 80.
Now I am a little stuck, and other solutions (e.g. creating a new vpn container, using a reverse proxy behind the vpn) are wasting a lot of resources, but switching Rotki from 80 to something else would solve the problem.

## Specification

Here is my docker-compose.yml right now
```yaml
services:

  vpn:
    image: ...
    ports:
      - 8000:80 # Rotki
      - 8001:80 # Container1
  
  container1: # Exposes port 80
    image: ...
    network_mode: service:vpn

  rotki: # Exposes port 80
    image: rotki/rotki
    network_mode: service:vpn
```
Accessing `localhost:8000` or `localhost:8001` will both direct me to rotki, or will both direct me to container1.

Unfortunately, the other container's development team has no problem ignoring requests :/

**Comment by kelsos** [comment]
@schklom can't you just use a port mapping in the rotki service itself?

What happens if you do something like: 

```yml
services:

  vpn:
    image: ...
    ports:
      - 8000:80 # Rotki
      - 8001:8001 # Container1
  
  container1: # Exposes port 80
    image: ...
    network_mode: service:vpn

  rotki: # Exposes port 80
    image: rotki/rotki
    network_mode: service:VPN
    ports:
      - 8001:80

```
